coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "tests/*"
  - "setup.py"
  - "*/__init__.py"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

parsers:
  python:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

codecov:
  require_ci_to_pass: yes

fixes:
  - "::src/cha_md_ba/"::"cha_md_ba/"
  - "::tests/"::"tests/" 